apiVersion: v1
kind: Pod
metadata:
  namespace: jenkins      
  name: multicontainers
  labels: 
    app: myapp1
    type: frontend   
spec: 
  containers:
    - name: jenkins
      image: jenkins/jenkins:lts
      resources:
        limits:
          cpu: 500m
          memory: 256Mi
        requests:
          cpu: 500m
          memory: 256Mi      
