apiVersion: v1
kind: Service
metadata:
  name: myservice
spec:
  type: nodeport
  selector:
    app: myapp1
  ports:
    - name: jenkins      
      protocol: TCP
      nodeport: 30001
      port: 8090
      targetPort: 8080
    - name: tomcat   
      protocol: TCP
      nodeport: 30100
      port: 8095
      targetPort: 8081
