apiVersion: v1
kind: Pod
metadata:
  name: multi-pod
  labels: 
    app: new
    type: new
spec:
  affinity:      
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - web
          topologyKey: kubernetes.io/hostname 
  containers:
    - name: jenkins
      image: jenkins/jenkins:lts
