apiVersion: v1
kind: Service
metadata: 
  name: replicaservice
spec: 
  type: NodePort
  selector:
    app: jenkinsreplica
  ports:
    - name: jenkins
      protocol: TCP
      port: 8080
      nodePort: 30010
      targetPort: 8080 
