apiVersion: v1
kind: Service
metadata:
  name: multisvc
spec:
  type: NodePort
  selector:
    app: myapp1
  ports:
    - name: jenkins
      protocol: TCP
      nodePort: 30001
      port: 8090
      targetPort: 8080
    - name: tomcat
      protocol: TCP
      nodePort: 30002
      port: 8095
      targetPort: 9090
