version: "3.8"
services:
  angular:
    build: ./Frontend
    ports:
      - "4300:80"
  express:
    build: ./Backend
    ports:
      - "5000:3000"
    expose:
      - "5000"
    links:
      - database
  database:
    image: "mongo"
  nginx:
    build: ./nginx
    restart: always
    ports:
      - "80:80"
    links:
      - express
      - angular     