apiVersion: apps/v1
kind: Deployment
metadata:
  name: arunreplica1
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector: 
    matchLabels:
      app: jenrep
  template:
    metadata: 
      name: mypod1
      labels: 
        app: jenrep
    spec: 
      containers:
        - name: tomcat
          image: tomcat:9.0  
