apiVersion: v1
kind: Service
metadata:
  name: my-service1
spec:
  selector:
    app: myapp1
  ports:
    - name: jenkins      
      protocol: TCP
      port: 30001
      targetPort: 8080
    - name: tomcat   
      protocol: TCP
      port: 30100
      targetPort: 8081
