apiVersion: v1
kind: Service
metadata:
  name: multisvcpod
spec:
  type: NodePort
  selector:
    app: myapp1
  ports:
    - name: jenkins
      protocol: TCP
      nodePort: 30121
      port: 8090
      targetPort: 8080
    - name: tomcat
      protocol: TCP
      nodePort: 30122
      port: 8095
      targetPort: 9090
