apiVersion: v1
kind: Service
metadata:
  name: repservice
spec:
  type: NodePort
  selector: 
    app: jenkinsreplica
  ports:
    - name: jen1
      protocol: TCP
      port: 8080
      nodePort: 30050
      targetPort: 8080
