apiVersion: apps/v1
kind: Deployment
metadata:
  name: arunreplica1
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 4
      maxUnavailable: 0
  selector: 
    matchLabels:
      app: jenkinsreplica1
  template:
    metadata: 
      name: mypod1
      labels: 
        app: jenkinsreplica1
    spec: 
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: environment
                  operator: In
                  values:
                    - dev
                    - qa
      containers:
        - name: jenkins
          image: jenkins/jenkins:lts             
