apiVersion: v1
kind: Pod
metadata: 
  name: multicontainers
  namespace: jenkins
  labels: 
    app: myapp1
    type: frontend   
spec: 
  containers:
    - name: jenkins
      image: jenkins/jenkins:lts
      resources: 
        limits: 
          cpu: 500m
          memory: 256Mi
        requests:
          cpu: 500m
          memory: 256Mi
