apiVersion: v1
kind: ResourceQuota
metadata:
  name: pod-quota
  namespace: jenkins
spec:
  hard:
    pods: "4"
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
