apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rep1
spec:
  replicas: 5
  selector: 
    matchLabels:
      app: jenrep
  template:
    metadata: 
      name: reppod
      labels: 
        app: jenrep
    spec: 
      containers:
        - name: jenkins
          image: jenkins/jenkins:lts  
